name: cat

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  do-the-good:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get random cat
      run: | 
        sh ./cat.sh
        git push "https://CatBot:${{ secrets.GITHUB_TOKEN }}@github.com/Gaunsessa/Gaunsessa.git"
