name: cat

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  random-cat:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get random cat
      run: | 
        bash ./cat.sh
        git push "https://CatBot:${{ secrets.GITHUB_TOKEN }}@github.com/Gaunsessa/Gaunsessa.git"
