name: TEST

on:
  workflow_dispatch:

jobs:
  do-the-good:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run test curl
      run: | 
        sh ./test.sh
        git push "https://CatBot:${{ secrets.GITHUB_TOKEN }}@github.com/Gaunsessa/Gaunsessa.git"
